---
project: deblur_gan
experiment_desc: fpn

train:
  files_a: &TRAIN_A ../data/REDS/train_blur/train_blur/*/*.png
  files_b: &TRAIN_B ../data/REDS/train_sharp/train_sharp/*/*.png
  files_c: &TRAIN_C ../data/REDS/train_maps/*/*.png
  # files_a: &TRAIN_A ./data/train/blurred_images/*.png
  # files_b: &TRAIN_B ./data/train/clear_images/*.png
  # files_c: &TRAIN_C ./data/train/attention_maps/*.png
  size: &SIZE 256
  crop: random
  preload: &PRELOAD false
  preload_size: &PRELOAD_SIZE 0
  bounds: [0, 1]
  scope: geometric
  corrupt: &CORRUPT
    - name: cutout
      prob: 0.5
      num_holes: 3
      max_h_size: 25
      max_w_size: 25
    - name: jpeg
      quality_lower: 70
      quality_upper: 90
    - name: motion_blur
    - name: median_blur
    - name: gamma
    - name: rgb_shift
    - name: hsv_shift
    - name: sharpen

val:
  files_a: &VAL_A ../data/REDS/val_blur/val_blur/*/*.png
  files_b: &VAL_B ../data/REDS/val_sharp/val_sharp/*/*.png
  files_c: &VAL_C ../data/REDS/val_maps/*/*.png
  # files_a: &VAL_A ./data/val/blurred_images/*.png
  # files_b: &VAL_B ./data/val/clear_images/*.png
  # files_c: &VAL_C ./data/val/attention_maps/*.png
  size: *SIZE
  scope: geometric
  crop: center
  preload: *PRELOAD
  preload_size: *PRELOAD_SIZE
  bounds: [0, 1]
  corrupt: *CORRUPT

phase: train
warmup_num: 3
model:
  g_name: saliency_net
  blocks: 9
  d_name: no_gan # may be no_gan, patch_gan, double_gan, multi_scale
  d_layers: 3
  content_loss: perceptual
  adv_lambda: 0.001
  disc_loss: wgan-gp
  learn_residual: True
  norm_layer: instance
  dropout: True

num_epochs: 20
train_batches_per_epoch: 2000
val_batches_per_epoch: 1500
batch_size: 2
image_size: [256, 256]

optimizer:
  name: adam
  lr: 0.0001
scheduler:
  name: linear
  start_epoch: 50
  min_lr: 0.0000001

